#!/usr/bin/with-contenv bash

[[ -n ${NETWORK6} && -z ${NET6_LOCAL} ]] && NET6_LOCAL=${NETWORK6}
if [ -n "$NET6_LOCAL" ]; then
   gw="$(ip -6 route | awk '/default/{print $3}')"
   for net in ${NET6_LOCAL//[;,]/ }; do
      echo "Enabling connection to network ${net}"
      ip -6 route | grep -q "$net" || ip -6 route add "$net" via "$gw" dev eth0
  done
fi